apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: ghcr.io/neerajnakka/nextjs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
          resources:
            requests:
              memory: '100Mi'
              cpu: '200m'
            limits:
              memory: '250Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
